name: Jarona
description: $description
version: '${version}'

main: pro.fazeclan.river.jarona.Jarona
bootstrapper: pro.fazeclan.river.jarona.JaronaBootstrap
loader: pro.fazeclan.river.jarona.JaronaLoader
api-version: '26.2'

authors: [ riversflowing ]

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    UnlimitedNameTags:
      load: BEFORE
      required: true
    NBTAPI:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true