name: Jarona
description: $description
version: '${version}'

main: pro.fazeclan.river.jarona.Jarona
api-version: '26.2'

authors: [ riversflowing ]

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    Sign:
      load: BEFORE
      required: true
    NBTAPI:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
    voicechat:
      load: BEFORE
      required: false